.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-MULTIUSER" "1" "October 2010" "" ""
.
.SH "NAME"
\fBnpm-multiuser\fR \-\- Set up npm in multiuser mode
.
.SH "SYNOPSIS"
.
.nf
sudo npm multiuser
.
.fi
.
.SH "DESCRIPTION"
This command can be used to set up a globally\-installed npm
to run in multi\-user mode, by putting node modules, executables,
and man pages in users\' home directories, so as to avoid the use
of sudo with untrusted code\.
.
.P
It will ask you to enter values for the various configuration
options, and then save those to the global config\.
.
.P
Follow the instructions on the screen\.
