.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "NPM\-SEARCH" "11" "May 2010" "" ""
.
.SH "NAME"
\fBnpm\-search\fR \-\- List packages matching a filter
.
.SH "SYNOPSIS"
.
npm search [filter]
.P
.SH "DESCRIPTION"
.P
This command will print to stdout all the versions of a package that
match the given arguments in their name, tags, or description. These
packages are accumulated from packages installed or available in the
registry, with their tags and whether or not they're active and/or
stable.
.
.P

The filter used represents a Javascript RegExp Object an has all the
features of such. It is case insensitive as well.
.
.P
To filter a single package or state, you can provide words to filter on
and highlight (if appropriate).  For instance, to see all the
packages relating to irc, you could do this:
.
.IP " " 4
npm search irc

